import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideHttpClient } from '@angular/common/http';
import {
   LucideArrowLeft,
   LucideArrowRight,
   LucideArrowUpDown,
   LucideBadgeCheck,
   LucideBuilding2,
   LucideCalendar,
   LucideCalendarFold,
   LucideClock,
   LucideChevronDown,
   LucideChevronLeft,
   LucideChevronRight,
   LucideCircleCheckBig,
   LucideCircleQuestionMark,
   LucideContactRound,
   LucideFileCheck,
   LucideFileText,
   LucideInfo,
   LucideLayoutDashboard,
   LucideLayoutGrid,
   LucideList,
   LucideListChecks,
   LucideLogOut,
   LucideMap,
   LucideMapPin,
   LucideMenu,
   LucideMessagesSquare,
   LucideMoon,
   LucidePaperclip,
   LucidePanelLeftClose,
   LucidePanelLeftOpen,
   LucideReceiptText,
   LucideSendHorizontal,
   LucideSettings,
   LucideSun,
   LucideTicket,
   LucideUser,
   LucideUserRound,
   LucideUsers,
   LucideX,
   provideLucideIcons
} from '@lucide/angular';
import { provideRouter } from '@angular/router';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
   providers: [
      provideBrowserGlobalErrorListeners(),
      provideHttpClient(),
      provideRouter(routes),
      provideLucideIcons(
         LucideArrowLeft,
         LucideArrowRight,
         LucideArrowUpDown,
         LucideBadgeCheck,
         LucideBuilding2,
         LucideCalendar,
         LucideCalendarFold,
         LucideClock,
         LucideChevronDown,
         LucideChevronLeft,
         LucideChevronRight,
         LucideCircleCheckBig,
         LucideCircleQuestionMark,
         LucideContactRound,
         LucideFileCheck,
         LucideFileText,
         LucideInfo,
         LucideLayoutDashboard,
         LucideLayoutGrid,
         LucideList,
         LucideListChecks,
         LucideLogOut,
         LucideMap,
         LucideMapPin,
         LucideMenu,
         LucideMessagesSquare,
         LucideMoon,
         LucidePaperclip,
         LucidePanelLeftClose,
         LucidePanelLeftOpen,
         LucideReceiptText,
         LucideSendHorizontal,
         LucideSettings,
         LucideSun,
         LucideTicket,
         LucideUser,
         LucideUserRound,
         LucideUsers,
         LucideX
      )
   ]
};
